name: 部署
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 检测
      uses: actions/checkout@master

    - name: 部署
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: .vuepress/dist/
        CNAME: wiki.typecho.love
